source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'MySampleApp' do
  use_frameworks!

  # Pods for MySampleApp

  pod 'AWSAuthCore', '~> 2.6.1'
  pod 'AWSS3', '~> 2.6.1'
  pod 'AWSDynamoDB', '~> 2.6.1'
  pod 'AWSPinpoint', '~> 2.6.1'
  pod 'AWSCognito', '~> 2.6.1'
  pod 'AWSAuthUI', '~> 2.6.1'
  pod 'AWSUserPoolsSignIn', '~> 2.6.1'
end
