//
//  UserIdentityViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSAuthCore

class UserIdentityViewController: UIViewController {
    
    @IBOutlet weak var userImageView: UIImageView!
    @IBOutlet weak var userName: UILabel!
    @IBOutlet weak var userID: UILabel!
    
    // MARK: - View lifecycle
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        let identityManager = AWSIdentityManager.default()
        
        if (AWSSignInManager.sharedInstance().isLoggedIn) {
            userName.text = NSLocalizedString("Authenticated User", comment: "Placeholder text for the authenticated in user.")
        } else {
            userName.text = NSLocalizedString("Guest User", comment: "Placeholder text for the guest in user.")
        }
        userID.text = identityManager.identityId
        userImageView.image = UIImage(named: "UserIcon")
        
    }
}
