//
//  UserEngageViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import AWSPinpoint
import UIKit
class UserEngageViewController: UIViewController {
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var addressLabel: UILabel!
    @IBOutlet weak var localeLabel: UILabel!
    @IBOutlet weak var platformLabel: UILabel!
    @IBOutlet weak var osVersionLabel: UILabel!
    
    let pinpointClient = AWSPinpoint(configuration: AWSPinpointConfiguration.defaultPinpointConfiguration(launchOptions: nil))
    
    override func viewDidLoad() {
        super.viewDidLoad()
        NotificationCenter.default.addObserver(self, selector:#selector(UserEngageViewController.onRemoteNotificationRegistered) , name: NSNotification.Name(rawValue: AppDelegate.remoteNotificationKey), object: nil)
        var userNotificationTypes : UIUserNotificationType
        userNotificationTypes = [.alert , .badge , .sound]
        let notificationSettings = UIUserNotificationSettings.init(types: userNotificationTypes, categories: nil)
        UIApplication.shared.registerUserNotificationSettings(notificationSettings)
        UIApplication.shared.registerForRemoteNotifications()
        let endpoint = pinpointClient.targetingClient.currentEndpointProfile()
        #if (arch(i386) || arch(x86_64))
            self.addressLabel.text = "Address: Push notifications only work on hardware devices."
        #else
            if let address = endpoint.address{
                self.addressLabel.text = "Address: \(address)";
            }
        #endif
        self.localeLabel.text = "Locale: \(endpoint.demographic!.locale!)"
        self.platformLabel.text = "Plaform: \(endpoint.demographic!.platform!)"
        self.osVersionLabel.text = "Platform Version: \(endpoint.demographic!.platformVersion!)"
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.scrollView.flashScrollIndicators()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        NotificationCenter.default.removeObserver(self)
    }
    
    @IBAction func seasonChanged(_ sender: UISegmentedControl) {
        let season = sender.titleForSegment(at: sender.selectedSegmentIndex)!
        let pinpointTargetingClient = pinpointClient.targetingClient
        pinpointTargetingClient.addAttribute([season], forKey: "seasons")
        pinpointTargetingClient.updateEndpointProfile()
    }
    
    func onRemoteNotificationRegistered()   {
        let endpoint = pinpointClient.targetingClient.currentEndpointProfile()
        #if (arch(i386) || arch(x86_64))
            self.addressLabel.text = "Address: Push notifications only work on hardware devices."
        #else
            if let address = endpoint.address{
                self.addressLabel.text = "Address: \(address)";
            }
        #endif
    }
    
}
